name:  Build  and  Test

on:
    pull_request:
        paths:
            -  "src/**"
            -  "tests/**"

jobs:
    build-test:
        runs-on:  ubuntu-latest
        steps:
            -  uses:  actions/checkout@v4
            -  uses:  actions/setup-dotnet@v4
                with:
                    dotnet-version:  "8.0.x"
            -  name:  Restore
                run:  dotnet  restore
            -  name:  Build
                run:  dotnet  build  --configuration  Release  --no-restore
            -  name:  Test
                run:  dotnet  test  --no-build  --configuration  Release
